### ISSUE TITLE
Custom System Commands Execute Error

### ISSUE THREAD

**Issue by qkevinto** [gdombiak/OctoPod#227]
Having a bit of trouble getting some custom system commands to execute.

I’ve added some custom system commands that does a curl to a webhook to turn some lights on and off, and it works fine when executing via the web interface but doesn’t seem to want to work through OctoPod.

I get a dialog saying “Warning: Failed to request to execute command”:

![C4CA0F0E-1DC6-41DA-9834-24CFB65F1E5A](https://user-images.githubusercontent.com/5260010/66084778-cb581e80-e5b2-11e9-9d37-e52090b62c87.png)

Any idea what’s going on here? The standard commands (shutdown, restart, etc.) works fine.

**Comment by gdombiak** [comment]
Hi Kevin,

It seems like you added those controls as system commands rather than [custom controls](http://docs.octoprint.org/en/master/features/custom_controls.html). You can add custom controls using this [convenient plugin](https://plugins.octoprint.org/plugins/customControl/). You should be good after that. 

Let me know how it goes.
Gaston

**Comment by gdombiak** [comment]
If you want to use them as system commands then check OctoPrint's logs to know the error code that is returning. I see in OctoPrint's documentation that any of these errors may be happening: http://docs.octoprint.org/en/master/api/system.html#execute-a-registered-system-command. Curious to hear which one you are running into.

Gaston

**Comment by qkevinto** [comment]
Thanks for the quick response @gdombiak :)

Adding them as a system command was intentional as I wanted to execute a shell command as opposed to sending GCODE to the printer.

BUT! I did manage to figure out the issue. When setting up a system action you set at least three fields, `action`, `command` and `name`. My problem was that I had a space in my `action` identifier:
```
system:
  actions:
  - action: Lights on
    command: curl -X POST https://maker.ifttt.com/trigger/prusa_lights_on/with/key/xxxx
    name: Lights on
```

However, this fixed it:
```
system:
  actions:
  - action: lightson
    command: curl -X POST https://maker.ifttt.com/trigger/prusa_lights_on/with/key/xxxx
    name: Lights on
```

Note that `Lights on` was changed to `lightson`.
