### ISSUE TITLE
System commands with spaces fail to execute

### ISSUE THREAD

**Issue by TheLion** [gdombiak/OctoPod#306]
Hi,

I use some custom scripts to set the brighness of the camera, without having to open the CLI.

![image](https://user-images.githubusercontent.com/3755011/79673783-10554280-81dd-11ea-8bff-067fe8fc3ca7.png)

Thsese work fine in Octoprint itself, and somewhere in the past (I don't use them very often, they also worked through the OctoPod app, but now they don't anymore

![image](https://user-images.githubusercontent.com/3755011/79673813-4692c200-81dd-11ea-9a0e-079da512a5e9.png)

The commands run a .sh script in the Pi home-folder.

The "Start video stream" and "Stop video stream" commands also run a .sh scripts in the Pi home-folder, and strangely enough, they do work.

**Comment by gdombiak** [comment]
This is interesting @TheLion. There are no recent changes made to system commands so not sure why it stopped working. Have you recently changed something else like updating OctoPrint?

BTW, if you can share your setup (e.g. config.yaml or how to add those system commands) I can try reproducing it and see what is going on.

Thanks,
Gaston

**Comment by TheLion** [comment]
> This is interesting @TheLion. There are no recent changes made to system commands so not sure why it stopped working. Have you recently changed something else like updating OctoPrint?

I did update OctoPrint to v1.40 a couple of weeks after it was released, but I'm not sure if that was the moment it stopped working. 

> BTW, if you can share your setup (e.g. config.yaml or how to add those system commands) I can try reproducing it and see what is going on.

I will share the part of config.yaml tomorrow,so hopefully you can reproduce it.

**Comment by gdombiak** [comment]
Thanks @TheLion. Once you shared the info I will see of reproducing this issue.

**Comment by TheLion** [comment]
The relevant part of the config is:

```
system:
    actions:
    -   action: streamon
        command: /home/pi/scripts/webcam start
        confirm: false
        name: Start video stream
    -   action: streamoff
        command: sudo /home/pi/scripts/webcam stop
        confirm: false
        name: Stop video stream
    -   action: setwebcam default
        command: sudo /home/pi/setwebcam.sh
        confirm: false
        name: Set Webcam Default
    -   action: setwebcam Exposure 800
        command: sudo /home/pi/setwebcam800.sh
        confirm: false
        name: Set Webcam Exposure 800
    -   action: setwebcam Exposure 400
        command: sudo /home/pi/setwebcam400.sh
        confirm: false
        name: Set Webcam Exposure 400
    -   action: setwebcam Exposure 200
        command: sudo /home/pi/setwebcam200.sh
        confirm: false
        name: Set Webcam Exposure 200
```

the .sh files contain, or something similar:

```
v4l2-ctl --set-ctrl=focus_auto=0 --verbose
v4l2-ctl --set-ctrl=focus_absolute=50 --verbose
v4l2-ctl --set-ctrl=exposure_auto=1 --verbose
v4l2-ctl --set-ctrl=exposure_auto_priority=0 --verbose
v4l2-ctl --set-ctrl=exposure_absolute=400 --verbose
v4l2-ctl --set-ctrl=sharpness=200 --verbose
v4l2-ctl --set-ctrl=white_balance_temperature_auto=0 --verbose
v4l2-ctl --set-ctrl=white_balance_temperature=6000 --verbose
```
If you need any more info, let me know.
